# Site settings
title: 'Generic Dev #65535'
email: 'thefirstmuffinman@gmail.com'
description: 'Writings and guides on everything Linux.'
baseurl: ""
url: "raeh.co"
twitter_username: raehik
github_username:  raehik

# Build settings
markdown: kramdown
permalink: pretty
