# Site settings
title: doing things on Linux
email: thefirstmuffinman@gmail.com
description: "Writings and guides on everything Linux."
baseurl: ""
url: "raeh.co"
twitter_username: jekyllrb
github_username:  raehik

# Build settings
markdown: kramdown
permalink: pretty
