# Site settings
title: Diaries of a Script Kiddie
email: thefirstmuffinman@gmail.com
description: Musings and guides on tech with a Linux slant.
url: raehik.github.io
twitter_username: raehik
github_username: raehik

# Build settings
markdown: RedcarpetCustom
permalink: pretty

# Default frontmatter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
