# Site settings
title: "Musings of a Linux dev"
email: "thefirstmuffinman@gmail.com"
description: "Guides on Linux things and essays on computer-related topics."
url: "raehik.github.io"
twitter_username: raehik
github_username: raehik

# Build settings
markdown: redcarpet
permalink: pretty

# Default frontmatter
defaults:
  -
    scope:
      path: ""
      type: "posts"
      type: "drafts"
    values:
      layout: "post"
