# Site settings
title: 'another Linux dev guy'
email: 'thefirstmuffinman@gmail.com'
description: 'Writings and guides on Linux-y bits. Also maybe other things!'
baseurl: ""
url: "raeh.co"
twitter_username: raehik
github_username:  raehik

# Build settings
markdown: kramdown
permalink: pretty
